---
# Sensitive Helm values. Store this file securely and do not commit rendered real secrets.
<%- if not database_external %>
postgresql:
  auth:
    password: "<< database_password >>"
<%- endif %>
<%- if not redis_external %>
redis:
  auth:
    password: "<< redis_password >>"
<%- endif %>
