---
apiVersion: v1
kind: Secret
metadata:
  name: << infisical_secret_name >>
  namespace: << namespace >>
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/instance: << release_name >>
type: Opaque
stringData:
  AUTH_SECRET: "<< infisical_auth_secret >>"
  ENCRYPTION_KEY: "<< infisical_encryption_key >>"
  SITE_URL: "<< infisical_site_url >>"
  <%- if redis_external %>
  REDIS_URL: "<< redis_url >>"
  <%- endif %>
  <%- if email_enabled %>
  SMTP_HOST: "<< email_host >>"
  SMTP_PORT: "<< email_port >>"
  SMTP_FROM_ADDRESS: "<< email_from_address >>"
  SMTP_FROM_NAME: "<< email_from_name >>"
  SMTP_USERNAME: "<< email_username >>"
  SMTP_PASSWORD: "<< email_password >>"
  SMTP_SECURE: "<< email_secure | lower >>"
  SMTP_REQUIRE_TLS: "<< email_require_tls | lower >>"
  SMTP_IGNORE_TLS: "<< email_ignore_tls | lower >>"
  <%- endif %>

